"""
Django settings for plateformeAutoML project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from django.urls import reverse_lazy

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = Path(__file__).resolve().parent

#Authentification
LOGIN_URL = reverse_lazy("connexion")
LOGIN_REDIRECT_URL = reverse_lazy("home")
LOGOUT_REDIRECT_URL = reverse_lazy("connexion")
USE_REMEMBER_ME = False
SESSION_SAVE_EVERY_REQUEST = True
#
AUTH_USER_MODEL = 'web_admin.Compte'
# test tes

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-os6^4h@w))&r$a08%#vjc1&vp)d6tcwppu1t1((_+_i)v*284!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', 'laima.automl']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'web_admin',
    # 'web_client',
    # 'web_vitrine',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


FILE_UPLOAD_HANDLERS = ("django_excel.ExcelMemoryFileUploadHandler",
                        "django_excel.TemporaryExcelFileUploadHandler")
                        
ROOT_URLCONF = 'plateformeAutoML.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'plateformeAutoML.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
    #On Docker ENV
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': os.environ.get('POSTGRES_NAME'),
    #     'USER': os.environ.get('POSTGRES_USER'),
    #     'PASSWORD': os.environ.get('POSTGRES_PASSWORD'),
    #     'HOST': 'db',
    #     'PORT': 5432,
    # }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'

# Add these new lines
STATICFILES_DIRS = [ BASE_DIR / 'static', ]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# os.path.join(BASE_DIR, 'static/images/upload')
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

UPLOAD_FOLDER = '/media/datasets'
MAX_CONTENT_LENGTH = 16 * 1024 * 1024 #16M
SEND_FILE_MAX_AGE_DEFAULT = 0


DATA_UPLOAD_MAX_MEMORY_SIZE = 500 * 1024 * 1024 * 1024 #500 MB
"""
Valeur par défaut : 2621440 (c-à-d. 2.5 Mio).
https://docs.djangoproject.com/fr/4.0/ref/settings/#std-setting-DATA_UPLOAD_MAX_MEMORY_SIZE
La taille maximale en octets d’un corps de requête avant qu’il ne provoque une exception SuspiciousOperation (RequestDataTooBig). 
Le contrôle est effectué lors de l’accès à request.body ou à request.POST et 
est calculé par rapport à la taille totale de la requête sans les données d’envoi de fichiers (uploads). 
Vous pouvez le définir à None pour désactiver le contrôle. Les applications susceptibles de recevoir des envois 
de formulaires inhabituellement volumineux devraient ajuster ce réglage.
La quantité de données de requête est corrélée à la quantité de mémoire nécessaire pour traiter la requête et remplir 
les dictionnaires GET et POST. Les grosses requêtes pourraient être utilisées comme vecteur d’attaque par déni de service 
si elles n’étaient pas contrôlées. Comme les serveurs Web n’effectuent en principe pas d’inspection approfondie des requêtes, 
il n’est pas possible de procéder à ce genre de contrôle à leur niveau.
"""
FILE_UPLOAD_MAX_MEMORY_SIZE = 500 * 1024 * 1024 #500 MB
"""
Valeur par défaut : 2621440 (c-à-d. 2.5 Mio).
La taille maximale (en octets) d’un téléversement avant qu’il ne soit déporté sur le système de fichiers. Voir Gestion des fichiers pour plus de détails.
"""

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'