

AUTHENTIFICATION -+++++

GESTION USER
    CREATION USER   -----
    UPDATE USER     ----
    DELETE          --

    PERMISSION      --
        MENU

CRUD BASIC ++---

CREATION PROJET
    CONTENU             -----
    CHARGEMENT FICHIER EXCELL ET PREVISUALISATION -----
    APPEL FONCITON BIBLIO AUTO ML   -----

