# Generated by Django 4.0.1 on 2022-02-14 21:56

from django.db import migrations, models
import django.db.models.deletion
import web_admin.enum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlgorithmeProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
                ('nombre_modele', models.IntegerField(blank=True, default=0, null=True)),
                ('algorthme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.algorithme')),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=254, null=True)),
                ('prenom', models.CharField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=254, null=True)),
                ('est_active', models.BooleanField()),
                ('etat', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CritereComparaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encodage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HyperParametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur_defaut', models.CharField(blank=True, max_length=254, null=True)),
                ('cle', models.CharField(blank=True, max_length=254, null=True)),
                ('type_donnee', models.CharField(choices=[('ENTIER', 'ENTIER'), ('DECIMAL', 'DECIMAL'), ('CAHINE_CARACTERE', 'CAHINE_CARACTERE'), ('INTERVALLE', 'INTERVALLE')], default=web_admin.enum.ETypeDonnee['DECIMAL'], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Imputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libele', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiseEchelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemin', models.CharField(blank=True, max_length=254, null=True)),
                ('precision', models.CharField(blank=True, max_length=254, null=True)),
                ('rapport', models.TextField(blank=True, max_length=254, null=True)),
                ('resume', models.TextField(blank=True, max_length=254, null=True)),
                ('algorithme_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.algorithmeprojet')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SymboleValeurManquante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbole', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxionomieTypeDonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeApprentissage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('prenom', models.CharField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pays', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True, max_length=254, null=True)),
                ('algorithme_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.algorithmeprojet')),
                ('hyper_parametre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.hyperparametre')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
                ('type_apprentissage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.typeapprentissage')),
            ],
        ),
        migrations.CreateModel(
            name='StrategieMiseEchelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
                ('mise_echelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.miseechelle')),
                ('taxionomie_type_donnee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.taxionomietypedonne')),
            ],
        ),
        migrations.CreateModel(
            name='StrategieImputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
                ('imputation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.imputation')),
                ('taxionomie_type_donnee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.taxionomietypedonne')),
            ],
        ),
        migrations.CreateModel(
            name='StrategieEncodage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
                ('encodage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.encodage')),
                ('taxionomie_type_donne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.taxionomietypedonne')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
                ('metrique', models.CharField(blank=True, max_length=254, null=True)),
                ('type', models.CharField(choices=[('ENTIER', 'ENTIER'), ('DECIMAL', 'DECIMAL'), ('CAHINE_CARACTERE', 'CAHINE_CARACTERE'), ('INTERVALLE', 'INTERVALLE')], default=web_admin.enum.ETypeDonnee['DECIMAL'], max_length=50)),
                ('est_publique', models.CharField(choices=[('EN_ATTENTE_VALIDATION', 'EN_ATTENTE_VALIDATION'), ('PUBLIC', 'PUBLIC'), ('PRIVE', 'PRIVE')], default=web_admin.enum.EEtatPublication['PRIVE'], max_length=50)),
                ('nombre_modele', models.IntegerField(blank=True, default=0, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
                ('type', models.CharField(choices=[('ENTIER', 'ENTIER'), ('DECIMAL', 'DECIMAL'), ('CAHINE_CARACTERE', 'CAHINE_CARACTERE'), ('INTERVALLE', 'INTERVALLE')], default=web_admin.enum.ETypeDonnee['DECIMAL'], max_length=50)),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.modele')),
            ],
        ),
        migrations.AddField(
            model_name='miseechelle',
            name='taxionomie_type_donnes',
            field=models.ManyToManyField(through='web_admin.StrategieMiseEchelle', to='web_admin.TaxionomieTypeDonne'),
        ),
        migrations.CreateModel(
            name='MetriqueAlgorithmeProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithme_projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.algorithmeprojet')),
                ('metrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.metrique')),
            ],
        ),
        migrations.CreateModel(
            name='MetriqueAlgorithme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.algorithme')),
                ('metrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.metrique')),
            ],
        ),
        migrations.AddField(
            model_name='metrique',
            name='algorithmes',
            field=models.ManyToManyField(through='web_admin.MetriqueAlgorithme', to='web_admin.Algorithme'),
        ),
        migrations.CreateModel(
            name='JeuDonnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.CharField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, max_length=254, null=True)),
                ('source', models.CharField(blank=True, max_length=254, null=True)),
                ('pourcentage_validation', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True)),
                ('pourcentage_test', models.DecimalField(blank=True, decimal_places=2, default=0.3, max_digits=3, null=True)),
                ('taille', models.IntegerField(blank=True, default=0, null=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.projet')),
            ],
        ),
        migrations.AddField(
            model_name='imputation',
            name='taxionomie_type_donnes',
            field=models.ManyToManyField(through='web_admin.StrategieImputation', to='web_admin.TaxionomieTypeDonne'),
        ),
        migrations.AddField(
            model_name='hyperparametre',
            name='valeurs',
            field=models.ManyToManyField(through='web_admin.Valeur', to='web_admin.AlgorithmeProjet'),
        ),
        migrations.AddField(
            model_name='encodage',
            name='strategie_encodages',
            field=models.ManyToManyField(through='web_admin.StrategieEncodage', to='web_admin.TaxionomieTypeDonne'),
        ),
        migrations.CreateModel(
            name='CritereComparaisonAlgorithme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.IntegerField(blank=True, default=0, null=True)),
                ('min', models.IntegerField(blank=True, default=0, null=True)),
                ('max', models.IntegerField(blank=True, default=0, null=True)),
                ('algorithme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.algorithme')),
                ('critere_comparaison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.criterecomparaison')),
            ],
        ),
        migrations.CreateModel(
            name='Colonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=254, null=True)),
                ('type_donnee', models.CharField(choices=[('ENTIER', 'ENTIER'), ('DECIMAL', 'DECIMAL'), ('CAHINE_CARACTERE', 'CAHINE_CARACTERE'), ('INTERVALLE', 'INTERVALLE')], default=web_admin.enum.ETypeDonnee['DECIMAL'], max_length=50)),
                ('est_categoriel', models.BooleanField()),
                ('est_target', models.BooleanField()),
                ('est_selectionnee', models.BooleanField()),
                ('pattern', models.CharField(blank=True, max_length=254, null=True)),
                ('jeu_donnees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.jeudonnees')),
                ('strategie_encodage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.strategieencodage')),
                ('strategie_imputation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.strategieimputation')),
                ('strategie_mise_echelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.strategiemiseechelle')),
            ],
        ),
        migrations.AddField(
            model_name='algorithmeprojet',
            name='metriques',
            field=models.ManyToManyField(through='web_admin.MetriqueAlgorithmeProjet', to='web_admin.Metrique'),
        ),
        migrations.AddField(
            model_name='algorithmeprojet',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.projet'),
        ),
        migrations.AddField(
            model_name='algorithme',
            name='famille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.famille'),
        ),
        migrations.AddField(
            model_name='algorithme',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.package'),
        ),
        migrations.AddField(
            model_name='algorithme',
            name='projet',
            field=models.ManyToManyField(through='web_admin.AlgorithmeProjet', to='web_admin.Projet'),
        ),
        migrations.AddField(
            model_name='algorithme',
            name='tache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.tache'),
        ),
    ]
