# Generated by Django 4.0.1 on 2022-04-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colonne',
            old_name='strategie_mise_echelle',
            new_name='strategie_normalisation',
        ),
        migrations.RenameField(
            model_name='colonne',
            old_name='type_donnee',
            new_name='type_donnees',
        ),
        migrations.RenameField(
            model_name='hyperparametre',
            old_name='type_donnee',
            new_name='type_donnees',
        ),
        migrations.RenameField(
            model_name='strategieencodage',
            old_name='taxionomie_type_donne',
            new_name='taxionomie_type_donnees',
        ),
        migrations.RenameField(
            model_name='strategieimputation',
            old_name='taxionomie_type_donnee',
            new_name='taxionomie_type_donnees',
        ),
        migrations.RenameField(
            model_name='strategiemiseechelle',
            old_name='taxionomie_type_donnee',
            new_name='taxionomie_type_donnees',
        ),
    ]
