# Generated by Django 4.0.1 on 2022-03-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compte',
            name='date_joined',
        ),
    ]
