# Generated by Django 4.0.1 on 2022-03-20 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0002_remove_compte_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='date_adhesion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
