# Generated by Django 4.0.1 on 2022-04-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0002_rename_strategie_mise_echelle_colonne_strategie_normalisation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategieencodage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='strategieencodage',
            name='libelle',
        ),
        migrations.RemoveField(
            model_name='strategieimputation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='strategieimputation',
            name='libelle',
        ),
        migrations.RemoveField(
            model_name='strategiemiseechelle',
            name='description',
        ),
        migrations.RemoveField(
            model_name='strategiemiseechelle',
            name='libelle',
        ),
        migrations.AddField(
            model_name='strategieencodage',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strategieimputation',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strategiemiseechelle',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
