# Generated by Django 4.0.1 on 2022-03-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0003_compte_date_adhesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='password',
            field=models.CharField(max_length=250),
        ),
    ]
