# Generated by Django 4.0.1 on 2022-04-06 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0004_algorithme_code_algorithmeprojet_code_colonne_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithme',
            name='famille',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.famille'),
        ),
        migrations.AlterField(
            model_name='algorithme',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.package'),
        ),
        migrations.AlterField(
            model_name='algorithme',
            name='projet',
            field=models.ManyToManyField(null=True, through='web_admin.AlgorithmeProjet', to='web_admin.Projet'),
        ),
        migrations.AlterField(
            model_name='algorithme',
            name='tache',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.tache'),
        ),
    ]
