# Generated by Django 3.2.5 on 2022-03-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0004_alter_compte_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='decription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='ville',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
