# Generated by Django 4.0.1 on 2022-04-07 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0005_alter_algorithme_famille_alter_algorithme_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategieencodage',
            name='code',
        ),
        migrations.RemoveField(
            model_name='strategieencodage',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='strategieimputation',
            name='code',
        ),
        migrations.RemoveField(
            model_name='strategieimputation',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='strategiemiseechelle',
            name='code',
        ),
        migrations.RemoveField(
            model_name='strategiemiseechelle',
            name='is_default',
        ),
        migrations.AddField(
            model_name='strategieencodage',
            name='description',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='strategieimputation',
            name='description',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='strategiemiseechelle',
            name='description',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='strategieencodage',
            name='taxionomie_type_donnees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.taxonomietypedonnee'),
        ),
        migrations.AlterField(
            model_name='strategieimputation',
            name='taxionomie_type_donnees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.taxonomietypedonnee'),
        ),
        migrations.AlterField(
            model_name='strategiemiseechelle',
            name='mise_echelle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.miseechelle'),
        ),
    ]
