# Generated by Django 4.0.1 on 2022-04-07 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0006_remove_strategieencodage_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategieimputation',
            name='imputation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.imputation'),
        ),
        migrations.AlterField(
            model_name='strategieimputation',
            name='taxionomie_type_donnees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.taxonomietypedonnee'),
        ),
    ]
