# Generated by Django 4.0.1 on 2022-04-07 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0007_alter_strategieimputation_imputation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strategieencodage',
            old_name='taxionomie_type_donnees',
            new_name='taxionomie_type_donnee',
        ),
        migrations.RenameField(
            model_name='strategieimputation',
            old_name='taxionomie_type_donnees',
            new_name='taxionomie_type_donnee',
        ),
        migrations.RenameField(
            model_name='strategiemiseechelle',
            old_name='taxionomie_type_donnees',
            new_name='taxionomie_type_donnee',
        ),
    ]
