# Generated by Django 4.0.1 on 2022-04-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0009_rename_taxionomie_type_donnee_strategieencodage_taxonomie_type_donnee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategieimputation',
            name='description',
            field=models.TextField(blank=True, default='', max_length=254, null=True),
        ),
    ]
