# Generated by Django 4.0.1 on 2022-04-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0010_alter_strategieimputation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithme',
            name='description',
            field=models.TextField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='algorithmeprojet',
            name='description',
            field=models.TextField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='criterecomparaison',
            name='description',
            field=models.TextField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='encodage',
            name='description',
            field=models.TextField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='famille',
            name='description',
            field=models.TextField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='imputation',
            name='description',
            field=models.TextField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='jeudonnees',
            name='description',
            field=models.TextField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='metrique',
            name='description',
            field=models.TextField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='miseechelle',
            name='description',
            field=models.TextField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='description',
            field=models.TextField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='projet',
            name='description',
            field=models.TextField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='strategieencodage',
            name='description',
            field=models.TextField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='strategieimputation',
            name='description',
            field=models.TextField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='strategiemiseechelle',
            name='description',
            field=models.TextField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='tache',
            name='description',
            field=models.TextField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='taxonomietypedonnee',
            name='description',
            field=models.TextField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='typeapprentissage',
            name='description',
            field=models.TextField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='description',
            field=models.TextField(blank=True, default='', max_length=254),
        ),
    ]
