# Generated by Django 4.0.1 on 2022-04-07 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0011_alter_algorithme_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategieencodage',
            name='encodage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.encodage'),
        ),
        migrations.AlterField(
            model_name='strategieencodage',
            name='taxonomie_type_donnee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_admin.taxonomietypedonnee'),
        ),
    ]
