# Generated by Django 4.0.1 on 2022-04-07 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0012_alter_strategieencodage_encodage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colonne',
            name='strategie_encodage',
        ),
        migrations.RemoveField(
            model_name='colonne',
            name='strategie_imputation',
        ),
        migrations.RemoveField(
            model_name='colonne',
            name='strategie_normalisation',
        ),
        migrations.AddField(
            model_name='colonne',
            name='encodage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.encodage'),
        ),
        migrations.AddField(
            model_name='colonne',
            name='imputation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.imputation'),
        ),
        migrations.AddField(
            model_name='colonne',
            name='normalisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.miseechelle'),
        ),
    ]
