# Generated by Django 4.0.1 on 2022-04-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0013_remove_colonne_strategie_encodage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithme',
            name='projet',
            field=models.ManyToManyField(through='web_admin.AlgorithmeProjet', to='web_admin.Projet'),
        ),
    ]
