# Generated by Django 4.0.1 on 2022-04-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0014_alter_algorithme_projet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='est_publique',
            new_name='statut',
        ),
        migrations.RenameField(
            model_name='projet',
            old_name='title',
            new_name='titre',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='type',
        ),
        migrations.AddField(
            model_name='projet',
            name='mots_cles',
            field=models.TextField(blank=True, default='', max_length=254),
        ),
    ]
