# Generated by Django 4.0.1 on 2022-04-14 18:21

from django.db import migrations, models
import django.utils.timezone
import web_admin.enum


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0015_rename_est_publique_projet_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='projet/image/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colonne',
            name='type_donnees',
            field=models.CharField(choices=[('ENTIER', 'entier'), ('DECIMAL', 'decimal'), ('CAHINE_CARACTERE', 'cahine caractere'), ('INTERVALLE', 'intervalle')], default=web_admin.enum.ETypeDonnee['DECIMAL'], max_length=50),
        ),
        migrations.AlterField(
            model_name='compte',
            name='etat',
            field=models.CharField(choices=[('ARCHIVE', 'archive'), ('EN_ATTENTE_VALIDATION', 'en attente validation'), ('ACTIF', 'actif')], default=web_admin.enum.EEtatCompte['ACTIF'], max_length=50),
        ),
        migrations.AlterField(
            model_name='hyperparametre',
            name='type_donnees',
            field=models.CharField(choices=[('ENTIER', 'entier'), ('DECIMAL', 'decimal'), ('CAHINE_CARACTERE', 'cahine caractere'), ('INTERVALLE', 'intervalle')], default=web_admin.enum.ETypeDonnee['DECIMAL'], max_length=50),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='type',
            field=models.CharField(choices=[('ENTIER', 'entier'), ('DECIMAL', 'decimal'), ('CAHINE_CARACTERE', 'cahine caractere'), ('INTERVALLE', 'intervalle')], default=web_admin.enum.ETypeDonnee['DECIMAL'], max_length=50),
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE_VALIDATION', 'en attente validation'), ('PUBLIC', 'public'), ('PRIVE', 'prive')], default=web_admin.enum.EEtatPublication['PRIVE'], max_length=50),
        ),
    ]
