# Generated by Django 4.0.1 on 2022-04-21 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0016_projet_image_alter_colonne_type_donnees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metriquealgorithmeprojet',
            name='algorithme_projet',
        ),
        migrations.RemoveField(
            model_name='metriquealgorithmeprojet',
            name='metrique',
        ),
        migrations.RenameField(
            model_name='metrique',
            old_name='libele',
            new_name='libelle',
        ),
        migrations.RemoveField(
            model_name='algorithmeprojet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='algorithmeprojet',
            name='libele',
        ),
        migrations.RemoveField(
            model_name='algorithmeprojet',
            name='metriques',
        ),
        migrations.RemoveField(
            model_name='algorithmeprojet',
            name='nombre_modele',
        ),
        migrations.RemoveField(
            model_name='metrique',
            name='algorithmes',
        ),
        migrations.AddField(
            model_name='algorithmeprojet',
            name='metrique',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web_admin.metrique'),
        ),
        migrations.AddField(
            model_name='metrique',
            name='tache',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web_admin.tache'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MetriqueAlgorithme',
        ),
        migrations.DeleteModel(
            name='MetriqueAlgorithmeProjet',
        ),
    ]
