# Generated by Django 4.0.1 on 2022-04-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0017_remove_metriquealgorithmeprojet_algorithme_projet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithmeprojet',
            old_name='algorthme',
            new_name='algorithme',
        ),
    ]
