# Generated by Django 4.0.1 on 2022-05-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0018_rename_algorthme_algorithmeprojet_algorithme'),
    ]

    operations = [
        migrations.AddField(
            model_name='colonne',
            name='valeurs',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
