# Generated by Django 4.0.1 on 2022-05-02 02:16

from django.db import migrations, models
import web_admin.enum


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0019_colonne_valeurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonne',
            name='est_categoriel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='colonne',
            name='est_selectionnee',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='colonne',
            name='est_target',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='colonne',
            name='type_donnees',
            field=models.CharField(choices=[('ENTIER', 'entier'), ('DECIMAL', 'decimal'), ('REEL', 'reel'), ('CAHINE_CARACTERE', 'cahine caractere'), ('INTERVALLE', 'intervalle')], default=web_admin.enum.ETypeDonnee['DECIMAL'], max_length=50),
        ),
        migrations.AlterField(
            model_name='hyperparametre',
            name='type_donnees',
            field=models.CharField(choices=[('ENTIER', 'entier'), ('DECIMAL', 'decimal'), ('REEL', 'reel'), ('CAHINE_CARACTERE', 'cahine caractere'), ('INTERVALLE', 'intervalle')], default=web_admin.enum.ETypeDonnee['DECIMAL'], max_length=50),
        ),
        migrations.AlterField(
            model_name='jeudonnees',
            name='description',
            field=models.TextField(blank=True, default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='type',
            field=models.CharField(choices=[('ENTIER', 'entier'), ('DECIMAL', 'decimal'), ('REEL', 'reel'), ('CAHINE_CARACTERE', 'cahine caractere'), ('INTERVALLE', 'intervalle')], default=web_admin.enum.ETypeDonnee['DECIMAL'], max_length=50),
        ),
    ]
