# Generated by Django 4.0.1 on 2022-05-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0020_alter_colonne_est_categoriel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonne',
            name='libelle',
            field=models.CharField(blank=True, default=None, max_length=254),
            preserve_default=False,
        ),
    ]
