# Generated by Django 4.0.1 on 2022-05-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0021_alter_colonne_libelle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonne',
            name='type_donnees',
            field=models.CharField(choices=[('ENTIER', 'entier'), ('DECIMAL', 'decimal'), ('REEL', 'reel'), ('CAHINE_CARACTERE', 'cahine caractere'), ('INTERVALLE', 'intervalle')], default='DECIMAL', max_length=50),
        ),
    ]
