# Generated by Django 4.0.1 on 2022-05-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0022_alter_colonne_type_donnees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonne',
            name='valeurs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
