# Generated by Django 4.0.1 on 2022-05-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0023_alter_colonne_valeurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeudonnees',
            name='pourcentage_entrainement',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True),
        ),
    ]
