# Generated by Django 3.2.7 on 2022-05-07 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0024_jeudonnees_pourcentage_entrainement'),
    ]

    operations = [
        migrations.AddField(
            model_name='modele',
            name='jeuDonnees',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web_admin.jeudonnees'),
            preserve_default=False,
        ),
    ]
