# Generated by Django 3.2.7 on 2022-05-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0025_modele_jeudonnees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonne',
            name='valeurs',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
