# Generated by Django 4.0.1 on 2022-05-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0026_alter_colonne_valeurs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modele',
            old_name='jeuDonnees',
            new_name='jeu_donnees',
        ),
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(upload_to='projet/images/%Y/%m/%d'),
        ),
    ]
