# Generated by Django 4.0.1 on 2022-06-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0027_rename_jeudonnees_modele_jeu_donnees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='image',
            field=models.ImageField(upload_to='projet/image/%Y/%m/%d'),
        ),
    ]
