# Generated by Django 4.0.1 on 2022-06-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_admin', '0028_alter_projet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='chemin',
            field=models.CharField(max_length=100),
        ),
    ]
